version: "3.9"

services:
  bot:
    build: .
    # host networking (ok for VPN/proxy use‑cases, just be aware of the security implications)
    network_mode: "host"
    environment:
      - DOWNLOAD_PATH=/app/data  # Force container path
      - HAMSTRA_TELEGRAM_CONFIG_DIR=/config
    command: ${CHATS}
    volumes:
      - "${HOST_DOWNLOAD_PATH}:/app/data"
      - "${HAMSTRA_TELEGRAM_CONFIG_DIR:-~/.config/hamstra/telegram}:/config"
    restart: unless-stopped